version: "3.8"

services:
  frontend:
    build:
      context: ./coup-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000 # Use o nome do serviço 'backend'
    depends_on:
      - backend
    networks:
      - coup-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - coup-network

networks:
  coup-network:
    driver: bridge
